### ISSUE TITLE
Splitting application and platform code

### ISSUE THREAD

**Issue by WardToulet** [stamhoofd/stamhoofd#117]
First let met define application and platform

**Platform**: everything to do with setting up an organization, invoicing for that organization and management of stamhoofd for that organization.
**Application**: the web application the users of stamhoofd interact with from day to day, being the management of there members, stores and events.

To allow for the self hosting of stamhoofd this should be split into two parts.

I propose two strategies for achieving this.

## Locking the platform features

Add an install script that creates an organzation in the beginning and locking the ability to add other organizations, creating in practice an instance of stamhoofd for a single organizations.

Pro:
- More compatible with the current state of stamhoofd

Contra:
- A lot of dead code that is never used in a single instance

## Splitting of the platform features

Running the platform features and the application features in a different process. 

Pro:
- This is a good separation of concerns
- This should make it more easy to dockerize the project

Contra:
- A new instance must be ran for each organization in the hosted version of stamhoofd.

**Comment by SimonBackx** [comment]
Personaly I think we need to go for your first strategy, but maybe a more hybrid approach. Splitting the platform features and having to run a separate process for each organization makes if a lot harder and inefficient to scale the platform itself, which is also a requirement. I also think the dead code will be very limited, and doesn't have any negative impact apart from the idea itself (as you don't need to load dead code in the frontend and it doesn't really matter in the backend). 

Currently we can still improve on separating organization specific logic, but it is split quite good already, e.g. each organization has its own API domain and associated endpoints. But still some development work is required to lock a local installation to a single organization. We also should consider splitting the organization selector / sign up from the dashboard itself in the future, and this could be replaceable with an installation system for a single installation (locking signing up a new organization as soon as the installation is complete).
