### ISSUE TITLE
[Feature] "Verzekerd" of "Ingeschreven" toevoegen aan lid

### ISSUE THREAD

**Issue by BoussonKarel** [stamhoofd/stamhoofd#122]
Met onze KSA moeten we gebruik maken van Digit om onze leden in te schrijven en dus ook te verzekeren. Het is moeilijk overzicht te bewaren welke er al in Digit zitten zonder dit handmatig te bekijken.

Integratie met digit is natuurlijk nog beter, als je dat kan regelen via KSA NAtionaal

**Comment by SimonBackx** [comment]
Momenteel werken we aan een functie waarmee je zelf extra kenmerken zal kunnen toevoegen aan de leden. De volgende stap is om ook de filters aan te passen, op die manier kan je een soort van overzicht maken met filters welke leden je nog in Digit moet toevoegen of nakijken :)

**Comment by SimonBackx** [comment]
+ Koppeling met Digit staan we zeker voor open. Hebben vorig jaar reeds eens contact gehad met KSA. Als zij een API beschikbaar maken, dan komt een koppeling sowieso op onze prioriteiten-todo.

**Comment by SimonBackx** [comment]
Feature requests kunnen via onze feedback tool. Dit staat trouwens gepland tegen september.
