### ISSUE TITLE
Beheerder invitelink downgrade hoofdbeheerder account

### ISSUE THREAD

**Issue by DaanVervacke** [stamhoofd/stamhoofd#140]
Wanneer je als hoofdbeheerder een beheerders invitelink accepteert wordt je account gedowngrade naar een beheerders account en verlies je toegang tot de instellingen van je organisatie. Je sluit jezelf dus (in ons geval perongeluk) buiten van je beheerdersaccount :)

**Comment by SimonBackx** [comment]
Dit is niet langer mogelijk met het nieuwe beheerders-invite systeem.
