### ISSUE TITLE
Broken functionality in mobile app

### ISSUE THREAD

**Issue by MartijnLeplae** [stamhoofd/stamhoofd#156]
Some features are not working in the mobile app (v 1.15.0): 

- Selecting/deselecting "wijzig zichtbare gegevens" (change visible data) has no effect, or shows strange behaviour.
- Moving people between groups using "verplaatsen naar>afdelingen>..." does not have any affect.

**Comment by SimonBackx** [comment]
@MartijnLeplae Can you recheck on v1.16.0? Are you using Android or iOS?

**Comment by MartijnLeplae** [comment]
The issue indeed seems to be resolved in v1.16.0! It was a problem on both iOS and Android.
