### ISSUE TITLE
[Feature] Toevoegen optie voor vrijwillige bijdrage/donatie

### ISSUE THREAD

**Issue by remcodehoon** [stamhoofd/stamhoofd#182]
In mijn omgeving zijn er verschillende clubs/stichtingen die hun leden een vrijwillige contributie/bijdrage laten betalen. D.w.z. dat een persoon zelf bepaalt wat deze kwijt wil. Een betaalverzoek/tikkie is vaak niet voldoende, omdat dan moeilijk te achterhalen is van wie deze bijdrage afkomstig is en deze verloopt.

Het zou dus mooi zijn als het ook mogelijk wordt om bij de prijs van een product voor een vrije input te kunnen kiezen.

**Comment by SimonBackx** [comment]
Je kan op dit idee stemmen via onze feedback tool, we gebruiken issues niet voor feature requests 😊

Dit idee is al gelijkaardig en kan je eventueel aanvullen met een reactie: https://feedback.stamhoofd.app/254
