### ISSUE TITLE
Privacy Foto's

### ISSUE THREAD

**Issue by StijnCornelis** [stamhoofd/stamhoofd#29]
Momenteel heb je de optie om aan te duiden of het kind al dan niet op een foto wilt. Is er ook een mogelijkheid waar de ouders/het kind kan aanduiden dat het enkel op groepsfoto's wilt. Wij hebben nu een aantal kinderen die enkel op groepsfoto's willen. Is het mogelijk om hier ook een selectievakje in te steken en tegen wanneer zou dit in orde kunnen zijn?

**Comment by SimonBackx** [comment]
Dat lijkt me zeker geen slecht idee! Als ouders geen toestemming geven voor gewone foto's kunnen we nog steeds een selectievakje zichtbaar maken om toch toestemming te geven voor groepsfoto's. Momenteel zijn er wel nog enkele andere grote prioriteiten, dus tenzij je zelf wat helpt om het toe te voegen zal het nog niet voor meteen zijn

**Comment by StijnCornelis** [comment]
Ik wil gerust helpen! Front-end zou me moeten lukken ;).
Tell me how I can help!

**Comment by SimonBackx** [comment]
Great :D 

Wel, de documentatie laat nog wat te wensen over. De projectstructuur is al een paar keer veranderd en de documentatie is daar nog niet op aangepast. 

Check even de repository stamhoofd/stamhoofd-structures, daarin vind je de data structuur van de API en front-ends. Leden hebben een property 'details' . Deze wordt in de front-end automatisch encrypted en decrypted, dus daar hoef je je geen zorgen over te maken.

In `records` wordt een lijst bijgehouden van de steekkaart. Daarin heb je `RecordType`.`NoData`. Daarin zou je eventueel een opmerking kunnen plaatsen dat groepsfoto's wel mogen. Die opmerking kan je dan zichtbaar maken in het dashboard voor de verenigingen zelf. 

Tis nog wat zoeken en heb momenteel niet super veel tijd om te documenteren omdat er enkele features zeker live moeten gaan tegen 1 september. Daarna heb ik hopelijk wat tijd voor documentatie. Je kan voorlopig al zeker eens rond kijken in de repo structuur, het meeste wijst zichzelf wel uit als je even wat zoekt :)

**Comment by SimonBackx** [comment]
Er zijn in ieder geval geen backend wijzigingen nodig voor deze functie

**Comment by SimonBackx** [comment]
#32
