### ISSUE TITLE
Registreren via site / portaal aanmaken lukt niet

### ISSUE THREAD

**Issue by woeterman94** [stamhoofd/stamhoofd#30]
![image](https://user-images.githubusercontent.com/5755057/91460516-28725800-e888-11ea-83c8-f27ee8432f5a.png)
![image](https://user-images.githubusercontent.com/5755057/91460545-32945680-e888-11ea-83fc-835659aef024.png)

**Comment by woeterman94** [comment]
Mogelijk is dit de oorzaak?
`{"errors":[{"id":"4c1c0ec1-d8eb-4294-a859-a1888157c752@1598541057759","code":"invalid_field","message":"Field is too short","human":"Kijk de naam van je organisatie na, deze is te kort","field":"organization.name"}]}`

Ik krijg in de front wel nergens een validatie fout

**Comment by SimonBackx** [comment]
Hmmm, dat laatste is mega waardevolle informatie! Ik denk inderdaad dat hij een 'sleutel' fout geeft terwijl dat eigenlijk niet het geval is. Ik kijk na voor een fix asap! Bedankt om het te melden!

**Comment by SimonBackx** [comment]
Opgelost! Ook validatie is gelijk getrokken tussen back-end en front-end, dus kan enkel in uitzonderingen nog voorkomen.
![image](https://user-images.githubusercontent.com/5277847/91486548-bb24ee00-e8ac-11ea-9cff-4b029c372ebd.png)

**Comment by SimonBackx** [comment]
@woeterman94 Had je een korte naam ingegeven puur om te testen of is de naam van jouw vereniging echt heel kort?

**Comment by woeterman94** [comment]
De naam is effectief heel kort.
