### ISSUE TITLE
Extra rol financieel verantwoordelijke

### ISSUE THREAD

**Issue by wutar** [stamhoofd/stamhoofd#33]
Vaak is de financieel verantwoordelijke (met toegang tot de bankrekening) iemand anders dan de verantwoordelijke voor de ledenlijst. Het zou handig zijn om in de modal voor "nieuwe beheerder" een checbox te hebben "toegang tot de financiën". Die persoon kan dan aangeven wie al dan niet overgeschreven heeft, maar niet perse de volledige ledenlijst zien.

**Comment by SimonBackx** [comment]
Goed idee, maar dit vergt wel nog wat werk qua permissions. Je kan de keuze maken om geen encryptie sleutel te geven aan de financieel verantwoordelijke (als hij geen toegang moet hebben tot de leden), maar dan kan je de volledige naam of contactgegevens niet tonen bij een overschrijving. 

Het zou ook kunnen dat we in de nabije toekomst de functie toevoegen om i.p.v. een gestructureerde mededeling, een mededeling in de vorm van "Lidgeld Simon Backx" in te stellen.

Enkele mogelijkheden:
- Encryptie blob opsplitsen in verschillende delen met verschillende encryptiesleutels, afhankelijk van bevoegdheid.
   - Het intrekken en uitgeven van permissies moet dan die encryptiesleutels op een goede manier kunnen uitkeren. En wat als een permissie ingetrokken wordt, dan moet die encryptiesleutel ook vernietigd worden en moeten eigenlijk alle leden opnieuw geencrypt worden (of je gaat ervan uit dat die data al bekend is en dus niet opnieuw versleuteld moet worden, maar wel bij aanpassingen de nieuwe sleutel moet gebruiken).
- Enkel voornamen weergeven bij overschrijvingen
- Nog steeds encryptiesleutel geven, maar puur op de leden endpoints restricties invoeren. Aangezien de payments opvragen ook de leden encryptie blobs terug geven is dit eigenlijk niet zo secure. Dit is dan eigenlijk meer een soort frontend side beveiliging, niet zo top.

Dit is dus nog wat werk, zal dus niet voor meteen zijn. Er moet dan eerst een systeem komen om meerdere encryptiesleutels voor een vereniging te hebben en om die op een stabiele manier met elkaar te laten samenwerken. Maar het is sowieso een feature die er moet komen.
