### ISSUE TITLE
Error bij mailadressen toevoegen

### ISSUE THREAD

**Issue by StijnCornelis** [stamhoofd/stamhoofd#34]
Wanneer ik mailadressen wil toevoegen aan onze stamhoofd krijg ik deze error, niet zo handig!

![image](https://user-images.githubusercontent.com/50902908/92308824-db396900-efa0-11ea-8281-7809fb2249b7.png)

**Comment by SimonBackx** [comment]
Bedankt voor te melden! Opgelost
