### ISSUE TITLE
QR Code betaling kapot zonder rekeningnummer

### ISSUE THREAD

**Issue by tomvaneyck** [stamhoofd/stamhoofd#38]
## Verwacht gedrag
Wanneer de groep geen rekeningnummer heeft ingesteld, wordt een lid/ouder daarvan op de hoogte gebracht bij de inschrijving. 

## Echt gedrag
Er wordt bij de betaling een qr-code gegenereerd zonder rekeningnummer, waardoor de qr-code niet werkt.

## Steps to Reproduce the Problem
- Maak een groep aan zonder rekeningnummer.
- Schrijf een lid in.
- Open de betaling, de qr-code werkt niet.

**Comment by SimonBackx** [comment]
Klopt, denk dat de QR-code dat niet echt ondersteunt. Eigenlijk zouden we het rekeningnummer verplicht moeten maken bij het maken van een vereniging, maar dat vind ik dan weer zo een grote drempel om het uit te proberen. Zou dan eerder een soort van 'testmode' introduceren waarbij je alles al kan uitproberen en om echt 'live' te gaan dat je eerst nog enkele stappen moet doorlopen. In deze testmode kunnen we dan een andere test-betaal-pagina tonen en de QR-code niet aanmaken.
