### ISSUE TITLE
Vrije mededeling betalingen

### ISSUE THREAD

**Issue by tomvaneyck** [stamhoofd/stamhoofd#39]
Bij de betaling via overschrijving zou een vrije mededeling moeten kunnen verkozen worden door de leiding i.p.v. een gestructureerde. Zo is het makkelijker bij te houden wie al heeft betaald.

Deze mededeling moet volgens een vast template gebeuren, zodat het voor de leiding duidelijk is over welke overschrijving het gaat. Het volgende template lijkt een goede keuze: `LIDGELD <voornaam> <achternaam> - <tak>, <voornaam> <achternaam> - <tak> ...`, waar de broers/zussen een voor een worden vermeld.

Aangezien de de qr-codestandaard maximum 140 karakters toelaat voor vrije mededelingen moet er bij betaling voor meerdere leden gecheckt worden of de namen deze lengte niet overschrijden. Indien dit wel gebeurt stel ik voor toch een gestructureerde mededeling te gebruiken, in tegenstelling tot delen van de namen weg te laten vallen of zelf een willekeurig getal te genereren, om het voorlopig simpel te houden. In de toekomst zou dit uitgebreid kunnen worden.

**Comment by SimonBackx** [comment]
We'll release this feature soon, but without mentioning age groups. The descriptions will become too long to enter. I'm afraid some parents won't enter the whole description (mainly less technical people) even without the age groups. Sadly, the QR-code isn't supported on some bank apps (while it is an European standard). We'll see how this evolves.
