### ISSUE TITLE
License change

### ISSUE THREAD

**Issue by SimonBackx** [stamhoofd/stamhoofd#41]
We decided to change our open-source Apache License 2.0 to the BSL 1.1 License. We made this change in advance to protect Stamhoofd against competitors, while still keeping if as free and open as possible. An important note here is that nothing changes for all our contributors and non-profit organizations, they can still keep using the source as long as they have fewer than 500 members. So you can still suggest new features, build them yourselves, help with bugfixes...

After 4 years, the source becomes open-source under the Apache License 2.0 and everyone is able to use it how they please. This new license will help protect Stamhoofd and it contributors and make sure we are in here for the long run, to build great software that will last. 

The only sad thing is that we can no longer call Stamhoofd open-source, as it is no longer possible for commercial companies and competitors to use it (only after 4 years). This is a requirement for open-source software, but we believe that this will damage Stamhoofd. 

An interesting read about this topic can be found at: https://blog.sentry.io/2019/11/06/relicensing-sentry

**Comment by WardToulet** [comment]
500 member limit

I was thinking of starting a similar project for my own organization (scouts) when I stumbled upon this project. I was exited to see other people working on this. 

I would like to contribute but as or group is around the 450 member mark and still growing (we are hoping to cap it in the next few years).
  
 What are my options if  our group exceeds the 500 member limit?

**Comment by SimonBackx** [comment]
@WardToulet We're happy to provide contributors with a separate (free) license if needed. 

We might announce some (big) news soon about future plans related to the licensing.

**Comment by SimonBackx** [comment]
I'm going to be open about this, and put this here. I'm **considering** to relicense again under GNU AGPLv3 to make the project open-source. However... I really like this project, a lot. It really want it to grow without having the need to grow the team behind it too much. In my opinion a big company also means slow progress, bad customer support, a decrease in UX and decisions only for short term wins. I want to avoid all those things. I want to contribute all my time in this project. The feedback I get from organizations is amazing (maybe because it is free :') ). I'm only able to do keep working on this — when it grows too much that it takes a lot of time for support etc. — if it somehow can pay my bills so I can quit my freelance work. I certainly don't want this project to become a big commercial thing. I like the idea of working in a small team on this project full-time (1 - 3 persons) and giving organizations the possibility to suggest and create changes themselves or host the solution on their own servers.

So the way the full-time team would be able to work on it full-time is by charging a small fee for the cloud solution (I've attached the current pricing idea below, feel free to give suggestions!). Current free users will always be able to stay on the free current offerings under a grandfathering system. But I'm not sure enough if enough people would actually want to pay for it. And I'm a bit scared of getting too much support work out of on-premise customers that do not pay or contribute to the project. I don't really mind that they use Stamhoofd, that just is great, but support often means building a support team that is able to handle this.

So, convince me why this project should be open-source and still a sustainable small business ;) Currently my mind is constatly swithcing between yes and no, so it's hard to make a long term decision (that's why I want to wait a bit to make a thoughtful decision). 

<img width="1173" alt="image" src="https://user-images.githubusercontent.com/5277847/107820441-17a49880-6d7b-11eb-83bf-c6e20872b2cc.png">
Please note these prices are still WIP. We could stil decide tol increase or decrease them.

**Comment by WardToulet** [comment]
I think it would be great to work under a true open-source license (:

For the company behind stamhoofd would you considering doing it under a not-profit (VZW) statue, I think it would be great to do it as a non profit because as you mentioned  the aim is not to become a big company, I also think there might be some options to get some governt funding for the project if it is managed by a non-profit (since it is helping non-profit i think it is worth looking into), which could lower the prices. You could be payed as a full time developer by the non-profit as could additional developers.

An other important source of revenue could be going more international, because the interface is only in dutch at the moment this could be a little tricky but I think that trying to attract interest in the Netherlands could be an interesting opportunity. I think scaling would be the only way to keep the prices low enough so organizations would be willing to pay for the service and you can make  enough revenue to allow you to work full time on stamhoofd.

**Comment by SimonBackx** [comment]
A non-profit is something I already considered, but there are some problems with the VZW entity in Belgium:
- You need at least 2 founders, and 3 directors. Currently, apart from myself we don't really have people that have already commited for the long term (some consider joining in the future and currently help part time, but it is still not sure if they want to keep doing this).
- Paying yourselves from a VZW is in Belgium not really allowed. A VZW is just not made to pay yourself. It gets edgy fast. It's not something a VZW was meant for. Also it is not possible to compensate for the first 2+ years of hard work without any revenue. 
- As an entrepreneur, you don't enjoy the same kind of rights as an employee. You don't have the same retirement, security system when you get ill or have an accident. So you need to take more risks and need to save more for when you are older. It seems fair that you can pay yourself a bit more than a normal employee to compensate this. So even when you are able to pay yourself, running as a VZW  doesn't allow for the **common** systems to reduce your taxes to a normal level. As an example: the government encourages you to keep your 'profit' 2+ years inside the business to have a buffer, in return you pay less taxes if you pay yourselves after 2+ years. As a result, entrepreneurs pay themselves very little actual salary and use these kind of systems (which the system was designed for). But that is considered as wealth, so this is not possible for non-profits. So in short: you'll pay more taxes on your sallary as a normal company and it will be harder to pay yourself that extra 'risk' or even the same as a normal employee.
- Subsidies is not something I want to rely upon. This also takes a lot of time and paperwork, so I would rather work on the product and company, which will probably yield far more returns (and is more fun).

A possible solution would be a private foundation. I still need to look into that. [Ghost](https://ghost.org) really a great example of what is possible. I really admire the way they work.

A non-profit is a great idea, but currently I would rather continue to run Stamhoofd on my freelance business (and start a separate company/non-profit as soon as we have a dedicated team) and run it as a non-profit instead of being a non profit. That means being transparent about financial things, numbers etc and invest back into a common cause, the society and the environment. We'll see in the future if we can move it into a non-profit structure. If that is not feasable: it's about the way you act. I don't think being a non-profit would have any big impact apart from having an official indication that you mean well (which doesn't prevent that you become evil eventually). Putting the source as an open-source license probably will have the most impact and secure the project from evil intruders.
