### ISSUE TITLE
Reduced price for brothers/sisters like 'standard price' minus 'discount'

### ISSUE THREAD

**Issue by nealjoos** [stamhoofd/stamhoofd#43]
In the current situation, it's only possible to configure a fixed reduced price for the second brother or sister, and a fixed reduced price for following brothers and sisters.
Some organizations might use a discount like the standard price - x EUR.

1st child: Standard price - 0x discount
2nd child: Standard price - 1x discount
3rd child: Standard price - 2x discount
4th child: Standard price - 3x discount
and so on.
It should be possible to configure a minimal price ofcourse ;)

**Comment by SimonBackx** [comment]
Now you can also add discounts for the 4th, 5th... family member, so you can have the same result :)
