### ISSUE TITLE
Signup stuck on creating keys in firefox

### ISSUE THREAD

**Issue by WardToulet** [stamhoofd/stamhoofd#45]
In the signup flow I keep getting stuck on the creating keys spinner.

This occurred on Firefox version 80.0b8. 
I have also tested this in chromium version  84.0.4147.135 where this issue did not occur.

Bot of these browsers run in arch linux.

**Comment by SimonBackx** [comment]
@AndreasBackx You had the same issue on linux?

**Comment by SimonBackx** [comment]
@WardToulet what specs does your computer have (memory, CPU)?

**Comment by WardToulet** [comment]
I have a skylake i7 (not shore which one) and 16GB of DDR3 memory, but I can't see why that would be an issue as the bugs does not occur chromium based browser on this machine.

I have not been able top test this on windows but I expect this to be an issue with Firefox and not my machine. 

To check this someone else should try to recreate the bug on Window.

**Comment by SimonBackx** [comment]
Okay, thanks for the update! I asked because we had similar issues in the past with devices that didn't had enough memory/CPU or had some sort of limit and killed the webworker that generated the keys. Key generation works on Firefox on Mac, so it is a combination with Firefox + Linux.

**Comment by SimonBackx** [comment]
I'm going to try to reproduce this issue first. 

We are also going to try is to create a separate build of libsodium for modern browsers (see issue  #https://github.com/jedisct1/libsodium.js/issues/263). I hope that will also improve the debugging experience and allow us to find the issue in the webworker or maybe it will solve this issue immediately.

**Comment by WardToulet** [comment]
This issue does no longer occur with the latest version of firefox on my machine.

**Comment by SimonBackx** [comment]
Could have been solved with an update to webpack + I downgraded libsodium due to an issue on iOS too. Need to rebuild libsodium with some changed settings.

**Comment by AndreasBackx** [comment]
I didn't get the chance to test this as I haven't had access to my Linux desktop for a while. Just got my desktop setup again this weekend. I can give this a shot again perhaps this weekend, though it was hard to reproduce last time as well. It didn't work the first time, but a refresh with a clear cache seemed to have resolved it back then.
