### ISSUE TITLE
External login providers

### ISSUE THREAD

**Issue by WardToulet** [stamhoofd/stamhoofd#57]
Managing user accounts can be a hassle for organizations, if parents or members have an account only used for stamhoofd many will forget the password or login, by supporting external login providers like Google,  Facebook or Microsoft using oauth or openid-connect. 

The organizations will have less overhead in supporting people who lost their login data.

Since openid-connect/OAuth (not entirely the same but interchangeable here for for now) are widely supported by the industry many people already have an account. 

Many providers can be added either as a setting from organization to organization or globally in stamhoofd.

This doesn't need to replace email login but can as it is on many sites on the internet an option for those who want to use it.

**Comment by SimonBackx** [comment]
I would LOVE external login providers. But how are you going to solve end-to-end encryption if you don't have a reliable way to save the keys on the web?

**Comment by SimonBackx** [comment]
You might disable end-to-end encryption for a part of the data (e.g. exclude the medical information). And require the users to re-enter the medical information every year.

**Comment by WardToulet** [comment]
Close because of other issue
