### ISSUE TITLE
Documentation and CLI tools for self hosted solution

### ISSUE THREAD

**Issue by SimonBackx** [stamhoofd/stamhoofd#60]
- [ ] Install scripts
- [ ] Build the frontend without needing to recompile for different domain configurations (maybe use in place replacement of specific variables)
- [ ] Split parts of Stamhoofd that are more 'platform' like and being able to host only a single organization
- [ ] Update scripts
- [ ] Documentation

**Comment by WardToulet** [comment]
I had some thoughts as how to document the back end endpoints as it can get very specify and I don't want to clutter this issue i have created one specific for the API documentation.
#62
