### ISSUE TITLE
MIgration 1593789706-keychain.sql failing on mysql

### ISSUE THREAD

**Issue by WardToulet** [stamhoofd/stamhoofd#64]
When running the migrations the migrations fails on the keychain migration with following error message.

`Error: ER_UNKNOWN_COLLATION: Unknown collation: 'utf8mb4_0900_ai_ci'`

When trying to run on myql version 5.7.31.

**Comment by SimonBackx** [comment]
Hmm, I think 5.x is not supported. You need to use MySQL 8 with legacy authentication.

**Comment by WardToulet** [comment]
This had indeed to do with the mysql version I bumped it in the docker-compose config
