### ISSUE TITLE
Mono repo managemet

### ISSUE THREAD

**Issue by WardToulet** [stamhoofd/stamhoofd#66]
The monorepo for stamhoofd provides benefits for development but makes it complex to manage dependencies. There are some existing projects that run on top of yarn workspace that try to tackle these issues, the main one seems to be [lerna](https://lerna.js.org/).

It might be interesting to start using it over bare yarn workspaces to make the dependency management easier.

**Comment by SimonBackx** [comment]
Normally you can install all the needed dependencies with yarn workspaces. What is the benefit of using lerna? I already checked it, but I couldn't find anything that would be usefull for Stamhoofd, but maybe I don't really understand what it does. Feel free to explain :)

**Comment by WardToulet** [comment]
I have done some further research into lerna and your  initial thoughts seems right,  for this project I don't see any benefits. My aim was to try and flatten the structure of the packages to increase the build time in docker but this should also be possible using bare yarn workspaces. On top of that lerna would add a significantly to the buildtime which is not that nice if it provides almost not benefits.
