### ISSUE TITLE
Add "Bus" to csv import.

### ISSUE THREAD

**Issue by amauryverschooren** [stamhoofd/stamhoofd#68]

**Comment by amauryverschooren** [comment]
Hi guys, I was missing the option to add the "bus" option of an address when i'm importing an excel file. I'm gonna try to solve this myself but i'm first gonna learn how this project is made and how the structure is. I'm studying ICT & Electronics in AP Hogeschool in Antwerpen. Mostly common with Angular/ionic TS and MySQL. I hope i can contribute to this project!

Kind regards Amaury.

**Comment by SimonBackx** [comment]
Great! Feel free to open a PR to fix this. We don't save the BUS separately, so you'll need to append it to the address number in the right order (it is possible the number is read after the bus)
