### ISSUE TITLE
Allow for importing bank transfer logs for checking manual transfers

### ISSUE THREAD

**Issue by WardToulet** [stamhoofd/stamhoofd#78]
When using regular transfers allow for the importing of the logs from the banking dashboard to automatically check if paimends are made.

**Comment by SimonBackx** [comment]
Yes, this is already on our roadmap :) But currently we have too many other things with a higher priority :/ But it's coming! :D

In the meantime, it would be nice if you already shared your bank + the format of the export in that bank. I know there are probably some standards for those exports (but I'm sure not all banks will support those)

**Comment by BoussonKarel** [comment]
https://www.isabel.eu/nl/multibanking/modules/coda.html

Uitreksels in digitaal formaat bestaan ook (CODA), maar dit is niet in elke rekening inbegrepen en vaak betalend (bv. paar euro per maand).

**Comment by RobinVanhove** [comment]
I might look into this later. @SimonBackx you mentioned that it is on the roadmap. Has any work been done that is not public yet?
