### ISSUE TITLE
Automatically re register

### ISSUE THREAD

**Issue by WardToulet** [stamhoofd/stamhoofd#80]
Allow for the creation of a policy that at the beginning of the new work year would add existing members to new groups (according to tags or something).  And send them billing information without their interaction.

**Comment by WardToulet** [comment]
I have given it some more thought and will provide an example.

# User
| USER     | TAGS |
|-|-|
| foo | 2002 JV2 |
| bar  | 2001 JV1 |
| bas | 2003 JV2 |
| fizz | 2002 JV3 |
| bus | 2001 JV1 |

I would enter some  combination of tags to add the correct members to groups. All members which are not assigned are also displayed.

Rules:
- JV1: (2002 OR 2003 OR 2004) AND JV1
- JV2: (2002 OR 2003 OR 2004) AND JV2
- JV3: (2002 OR 2003 OR 2004) AND JV3

This will add the members to their group from last year if they are still eligible and allows for easy tagging of the members which need to be divided.

An addition could be some kind of pseudo groups for members that need to be assigned, either manually or by these rules.

One more idea is to make a nested rulesetfor this for example

2002 OR 2003 OR 2004
    JV1 -> jv1
    JV2 -> jv2
    JV3 -> jv3
    _     -> jvX

This is simmilare to pattern matching in some languages. And could be done in a drag and drop interface.

PS: the reason i am using tags for the birth year instead of suggesting looking at the members birthday is that some members are not in there normal birth group often because the skipped or doubled a year in school.

**Comment by SimonBackx** [comment]
Not a bad idea, but how would you handle members that quit? Add an option in the e-mail for that?

**Comment by WardToulet** [comment]
In our current (manual) workflow we assume no member quits, but if they don't show up during one of the first activities (first month)  they are contacted and removed from the list.

**Comment by SimonBackx** [comment]
Okay. For this to work we first need to build a system to add manual transfer (or maybe even online payment methods) information from the dashboard. Next, we'll need a feature to be able to send that transfer information via e-mails. The next steps are easy:
- When starting a new registration period, add an option to move all members to the new registration period/cycle, and to automatically calculate the corresponding group(s). Eventually add an UI to handle non-solveable group transitions.
- Create the payments and open the e-mail UI to send an e-mail to all these members with the transfer information attached.

**Comment by SimonBackx** [comment]
We also received some more questions about spread payments and payment deadlines. And they share a common problem we have to add these features. I don't think it is a good idea to send transfer or payment instructions via e-mail. With the high amount of more realistic phishing emails today, we should avoid doing this and conform to best practices: never send payment instructions via email. But that makes these kind of features very hard to implement. We should think very carefully about how we are going to solve this issue first.
