### ISSUE TITLE
[Feature] Confirmation mail after signing up a member to a group

### ISSUE THREAD

**Issue by maltsavkiryl** [stamhoofd/stamhoofd#96]
I think it would be nice to receive a confirmation mail with the info of registration + payment details (for manual transfers) after signing up to a group as a member.

What do ya think?

**Comment by SimonBackx** [comment]
Yes please! We just need a way to customize the message on an organizational level and also make it possible to add a text per group (with extra instructions or something). Feel free to quickly sketch some mockups on a notepad and propose how you want to build it. Implementation should be very straighforward

**Comment by maltsavkiryl** [comment]
Making a html template for email is pretty easy. We just have to create a couple of specific templates that need some required parameters to be filled in. This would be a proposal for the "generic" emails you receive from stamhoofd

![stamhoofd_email_mockup](https://user-images.githubusercontent.com/12672784/122387012-b67e1300-cf6e-11eb-9f76-fb03c8c34857.png)

**Comment by maltsavkiryl** [comment]
Making a html template for email is pretty easy. We just have to create a couple of specific templates that need some required parameters to be filled in. This would be a proposal for the template for "generic" emails you receive from stamhoofd.

![stamhoofd_email_client_mockup](https://user-images.githubusercontent.com/12672784/122387739-779c8d00-cf6f-11eb-9609-0a7fc0d89d8e.png)

**Comment by maltsavkiryl** [comment]
What do you exactly mean with 
> "a way to customize the message on an organizational level and also make it possible to add a text per group (with extra instructions or something)."

Do we want to allow the users to configure the messages that get sent to the members when they signup? Or when they place an order in the webshop?

I would propose to have as little configuration as possible in the first stage. I love software that does everything by itself without having to configure it too much.

**Comment by maltsavkiryl** [comment]
And something like this for confirmation of registration:

![bevestigingsmail_inschrijving_mockup](https://user-images.githubusercontent.com/12672784/122401934-5478da00-cf7d-11eb-89d2-b27391c6d79c.png)

**Comment by maltsavkiryl** [comment]
And something like this for confirmation of registration:

![bevestigingsmail_inschrijving_mockup](https://user-images.githubusercontent.com/12672784/122402450-c7825080-cf7d-11eb-9c7b-299101bd0639.png)

**Comment by SimonBackx** [comment]
Still needed before we can start building this feature:

- [ ] Mockups/sketches of the admin/dashboard side: how will you enable this feature, how will you edit the templates...

For the first version, I would only use emails without HTML and keep them in plaintext. That will save a lot of time and help ship the feature faster.
